services:
  api1: &api1
    image: lucasmolinari/rbe26-api:latest
    environment:
      - VECTORS_PATH=/app/resources/vectors.bin
    deploy:
      resources:
        limits:
          cpus: "0.425"
          memory: "170MB"

  api2:
    <<: *api1
    environment:
      - VECTORS_PATH=/app/resources/vectors.bin

  lb:
    image: lucasmolinari/rbe26-lb:latest
    ports:
      - "9999:9999"
    environment:
      - UPSTREAMS=api1:9999,api2:9999
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "10MB"
